### ISSUE TITLE
Last value of last row not retrieved

### ISSUE THREAD

**Issue by mikeequinto** [eadgyo/Extract-PDF-Excel#3]
Hi there,

Thanks for this great PDF to Excel converter! However, there is one problem which I noticed, it seems that the last value of the last row is not retrieved when converting to excel.

Will there be a fix for this?

Thanks,
Mikee

**Comment by patatohead** [comment]
Hi,

I have the samen problem. Is it possible to solve this somehow?

Thanks in advance,
Joost

**Comment by eadgyo** [comment]
Hello Joost, I will take a look this week and let you know when it will be
fixed.
Ronan.

**Comment by patatohead** [comment]
Thanks Ronan! Any news yet? (no pressure)

**Comment by patatohead** [comment]
> Hello Joost, I will take a look this week and let you know when it will be fixed. Ronan.
> […](#)

Is there any news?
Thanks, Joost

**Comment by eadgyo** [comment]
I'm sorry i didn't have time. I have to put some time to fix the issue. I might have to do a redo to improve the general code structure and algorithm.

**Comment by patatohead** [comment]
Hi Ronan, is it still possible that there will be a solution for this issue? If not, no problem, but it would be extremly appriciated.

**Comment by eadgyo** [comment]
Yeah, sorry about the delay.
I have some game projects on track. I should take time this week. I really
want to fix the bug.
Sincerely,
Ronan.

**Comment by eadgyo** [comment]
The problem with the last value not being treated has been treated.
Sincerly,
ronan.
