### ISSUE TITLE
Failed to pull form fill data

### ISSUE THREAD

**Issue by starhound** [eadgyo/Extract-PDF-Excel#4]
When ran as directed from the Readme

> wesley@Main-002 MINGW64 ~/Downloads
$ java -jar pdfconvert.jar PL-BLANK.pdf result.xls
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.itextpdf.text.io.ByteBufferRandomAccessSource$1 (file:/C:/Users/Wesley/Downloads/pdfconvert.jar) to method java.nio.DirectByteBuffer.cleaner()
WARNING: Please consider reporting this to the maintainers of com.itextpdf.text.io.ByteBufferRandomAccessSource$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

Also did not preserve data generated from a form fill PDF.

**Comment by starhound** [comment]
See side by side output of XLS and PDF: https://imgur.com/u1KBnV7

**Comment by eadgyo** [comment]
I will look into fill formed data.

**Comment by eadgyo** [comment]
The support for filled forms has been added in the last commit. Feel free to test. 
The traitement is a bit different from text content, so if you encounter any trouble, send me an example pdf.

For the illegal access, i'm accessing some private methods and variables from itext.
